### ISSUE TITLE
Failed to activate the open-doc package

### ISSUE THREAD

**Issue by prometheas** [190n/open-doc#4]
Heyo — ever since this latest update, I'm getting this message for _every_ project window I open in Atom:

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [open-doc](https://github.com/fogcityben/open-doc) package, v0.3.5
### Stack Trace

Failed to activate the open-doc package

```
At 0 is not a valid selector in /Users/lianoglj/.atom/packages/open-doc/package.json

SyntaxError: 0 is not a valid selector in /Users/lianoglj/.atom/packages/open-doc/package.json
  at exports.validateSelector (/Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/node_modules/clear-cut/index.js:115:19)
  at CommandRegistry.module.exports.CommandRegistry.add (/Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:47:9)
  at /Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:817:70
  at Package.module.exports.Package.subscribeToActivationCommands (/Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:846:11)
  at Package.module.exports.Package.subscribeToDeferredActivation (/Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:803:12)
  at /Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:30
  at Package.module.exports.Package.measure (/Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
  at /Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:469:29
  at Config.module.exports.Config.transact (/Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:464:19)
  at PackageManager.module.exports.PackageManager.activate (/Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:46)
  at Atom.module.exports.Atom.startEditorWindow (/Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:673:21)
  at Object.<anonymous> (/Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/static/index.js:96:23)
  at window.onload (file:///Users/lianoglj/Applications/Atom.app/Contents/Resources/app.asar/static/index.js:36:7)

  at /Users/lianoglj/.atom/packages/open-doc/package.json:1:1
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "debugger",
      "wrap-guide",
      "Clean2",
      "json-schema",
      "quick-editor"
    ]
  },
  "open-doc": {}
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
api-docs, v0.0.3
atom-chai-snippets, v0.3.0
atom-macros, v0.5.1
atom-phpcs, v0.8.0
atom-ternjs, v0.7.1
autocomplete-php, v0.3.6
caniuse, v0.5.5
clipboard-plus, v0.5.1
docblockr, v0.7.3
editorconfig, v1.0.1
external-open, v0.6.1
flex-tool-bar, v0.4.4
foldingtext-for-atom, v0.9.0
formatter, v2.12.3
git-tab-status, v1.9.2
imdone-atom, v1.1.15
jsformat, v0.9.0
language-diff, v0.3.0
language-gherkin, v1.0.2
line-ending-converter, v1.2.0
linter, v1.3.2
linter-csslint, v1.0.5
linter-jshint, v1.1.4
linter-php, v1.0.3
linter-phpcs, v1.0.6
linter-scss-lint, v2.0.0
minimap, v4.12.2
minimap-bookmarks, v0.1.0
minimap-git-diff, v4.1.7
minimap-linter, v1.0.0
nucleus-dark-ui, v0.1.3
package-manager-commands, v2.0.3
php-composer-completion, v0.3.2
php-introspector, v1.0.0
phpunit, v1.1.1
pigments, v0.9.3
project-manager, v1.15.11
set-syntax, v0.3.0
seti-syntax, v0.4.0
travis-ci-status, v0.16.0
vagrant, v0.1.0
wakatime, v4.0.12

# Dev
No dev packages
```

**Comment by 190n** [comment]
Can you paste the contents of your `~/.atom/packages/open-doc/package.json` here? I've looked through what's in the repository and there doesn't seem to be anything wrong.

**Comment by 190n** [comment]
Fixed in v0.3.6 (86def38). Never mind about the package.json.

**Comment by einfallstoll** [comment]
**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [open-doc](https://github.com/190n/open-doc) package, v0.3.7

### Stack Trace

Failed to activate the open-doc package

```
At Cannot read property 'file' of undefined

TypeError: Cannot read property 'file' of undefined
    at Object.module.exports.activate (/Users/fabiopoloni/.atom/packages/open-doc/lib/open-doc.coffee:5:60)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:00.8.0 open-doc:open (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-htmlhint"
    ],
    "packagesWithKeymapsDisabled": [
      "open-on-github",
      "git-diff"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
language-ejs, v0.2.0
linter, v1.11.4
linter-jshint, v2.1.0
linter-php, v1.2.0
merge-conflicts, v1.4.3
open-doc, v0.3.7
pigments, v0.26.3
project-manager, v2.9.7

# Dev
No dev packages
```

**Comment by 190n** [comment]
@einfallstoll it seems that the latest Atom has broken open-doc.

I am no longer maintaining open-doc. You should use a different package instead. Searching for `open` on Atom's package page gives some good results. I just tested open-in-browsers, and it works well.

**Comment by prometheas** [comment]
Awesome avatar, @190n.
